CREATE TABLE PRODUCTOS_PRO(
idproducto number(3) PRIMARY KEY,
nombre varchar2(20),
descripcion varchar2(25),
precio number(6,2),
stock number (3),
categoria varchar2 (20),

);

CREATE TABLE USUARIOS_PRO(
idusuario number(3) PRIMARY KEY,
nombre varchar2(20),
email varchar2(35),
password varchar2 (30),
administrador number (1)
);

CREATE TABLE PEDIDOS_PRO(
IDPEDIDO NUMBER (3) PRIMARY KEY,
FECHAPEDIDO DATE,
IDUSUARIOS NUMBER (3) REFERENCES USUARIOS_PRO
);

CREATE TABLE LINEAS_PEDIDOS_PRO (
IDPEDIDO NUMBER (3) REFERENCES PEDIDOS_PRO,
IDPRODUCTO NUMBER (3) REFERENCES PRODUCTOS_PRO,
CANTIDAD NUMBER (3),
PRECIO NUMBER (6,2),
IMPORTE NUMBER (5,2)
);

INSERT INTO PRODUCTOS_PRO VALUES (1,'LAPIZ','LAPIZ NORMAL',2.50,0,'MATERIAL CLASE');
INSERT INTO PRODUCTOS_PRO VALUES (2,'CALCULADORA','CALCULADORA CIENTIFICA',20.00,5,'MATERIAL CLASE');
INSERT INTO PRODUCTOS_PRO VALUES (3,'GOMA DE BORRAR','GOMA DE BORRAR DE MILAN',1.50,30,'MATERIAL CLASE');
INSERT INTO PRODUCTOS_PRO VALUES (4,'PANTALLA','PANTALLA HP BLACK',190.00,5,'PERIFERICOS');
INSERT INTO PRODUCTOS_PRO VALUES (5,'TECLADO','TECLADO LOGITECH',47.99,17,'PERIFERICOS');
INSERT INTO PRODUCTOS_PRO VALUES (6,'RATÓN','RATON RAZER NEGRO',60.99,0,'PERIFERICOS');
INSERT INTO PRODUCTOS_PRO VALUES (7,'BOLIGRAFOS','BOLIGRAFO BIC AZUL',2.00,2,'MATERIAL CLASE');

INSERT INTO USUARIOS_PRO VALUES (1,'CAMILO','camilo@zabalburu.org','12345',0);
INSERT INTO USUARIOS_PRO VALUES (2,'UNAI','unai@zabalburu.org','67890',0);
INSERT INTO USUARIOS_PRO VALUES (3,'ANDER','ander@zabalburu.org','45678',1);
INSERT INTO USUARIOS_PRO VALUES (4,'MAITE','maite@zabalburu.org','24680',0);
INSERT INTO USUARIOS_PRO VALUES (5,'MARTINA','martina@zabalburu.org','13579',1);

INSERT INTO PEDIDOS_PRO VALUES (1,'02/05/2025',1);
INSERT INTO PEDIDOS_PRO VALUES (2,'11/05/2025',1);
INSERT INTO PEDIDOS_PRO VALUES (3,'17/05/2025',1);
INSERT INTO PEDIDOS_PRO VALUES (4,'20/05/2025',1);

INSERT INTO LINEAS_PEDIDOS_PRO VALUES (1,1,6,2.5,null);
INSERT INTO LINEAS_PEDIDOS_PRO VALUES (1,2,6,20.00,null);
INSERT INTO LINEAS_PEDIDOS_PRO VALUES (1,4,2,190.00,null);
INSERT INTO LINEAS_PEDIDOS_PRO VALUES (1,5,7,47.00,null);

UPDATE LINEAS_PEDIDOS_PRO SET IMPORTE = CANTIDAD*PRECIO;

SELECT NOMBRE,EMAIL,PASSWORD
FROM USUARIOS_PRO
WHERE ADMINISTRADOR = 1
ORDER BY NOMBRE;

SELECT * FROM PRODUCTOS_PRO
WHERE PRECIO >= 1.50 AND PRECIO <= 20
ORDER BY NOMBRE;


DROP TABLE USUARIOS_PRO CASCADE CONSTRAINTS;
DROP TABLE PRODUCTOS_PRO CASCADE CONSTRAINTS;
DROP TABLE PEDIDOS_PRO CASCADE CONSTRAINTS;
DROP TABLE LINEAS_PEDIDOS_PRO CASCADE CONSTRAINTS;

