--------------------------------------------------------
-- Archivo creado  - lunes-mayo-26-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Function VER_PRODUCTOS_SUMA
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE FUNCTION "DAW1"."VER_PRODUCTOS_SUMA" 
(
    P_PEDIDO IN NUMBER 
    
) RETURN NUMBER AS 

V_NOMBRE PRODUCTOS_PRO.NOMBRE%TYPE;
V_STOCK PRODUCTOS_PRO.STOCK%TYPE;
V_TOTAL NUMBER (5,2):=0;

CURSOR C_PRODUCTOS IS
SELECT * FROM LINEAS_PEDIDOS_PRO WHERE IDPEDIDO = P_PEDIDO;

BEGIN

FOR V_PRODUCTO IN C_PRODUCTOS
LOOP

SELECT STOCK INTO V_STOCK FROM PRODUCTOS_PRO WHERE IDPRODUCTO = V_PRODUCTO.IDPRODUCTO;
SELECT NOMBRE INTO V_NOMBRE FROM PRODUCTOS_PRO WHERE IDPRODUCTO = V_PRODUCTO.IDPRODUCTO;

IF V_STOCK !=0 THEN
V_TOTAL := V_TOTAL + V_PRODUCTO.IMPORTE;
END IF;

END LOOP;

RETURN V_TOTAL;
RETURN V_NOMBRE;
END VER_PRODUCTOS_SUMA;

/
