DECLARE 
P_PEDIDO PEDIDOS_PRO.IDPEDIDO%TYPE;
V_NOMBRE PRODUCTOS_PRO.NOMBRE%TYPE;
V_RESULTADO NUMBER(5,2);
BEGIN 

V_NOMBRE:='&NOMBRE PRODUCTO';
P_PEDIDO:='&ID_PEDIDO';


V_RESULTADO:=VER_PRODUCTOS_SUMA (P_PEDIDO);
DBMS_OUTPUT.PUT_LINE('NOMBRE DEL PRODUCTO: ' || V_NOMBRE);
DBMS_OUTPUT.PUT_LINE('SUMA DE PRECIO: ' || V_RESULTADO);
END;