--------------------------------------------------------
-- Archivo creado  - lunes-mayo-26-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Procedure P_DATOS_PRODUCTOS
--------------------------------------------------------
set define off;

  CREATE OR REPLACE NONEDITIONABLE PROCEDURE "DAW1"."P_DATOS_PRODUCTOS" 
(P_NOMBRE_PRODUCTO IN VARCHAR2 
)AS

V_DATOS_PRODUCTOS_PRO PRODUCTOS_PRO%ROWTYPE;
V_ACTIVO_PRODUCTO char(3);

BEGIN
    SELECT * INTO V_DATOS_PRODUCTOS_PRO 
    FROM PRODUCTOS_PRO
    WHERE UPPER(NOMBRE) = UPPER(P_NOMBRE_PRODUCTO);
    
    DBMS_OUTPUT.PUT_LINE('ID_PRODUCTO Nº ' || V_DATOS_PRODUCTOS_PRO.IDPRODUCTO);
    DBMS_OUTPUT.PUT_LINE('NOMBRE DE PRODUCTO ' || P_NOMBRE_PRODUCTO);
    DBMS_OUTPUT.PUT_LINE('DESCRIPCION ' || V_DATOS_PRODUCTOS_PRO.DESCRIPCION);
    DBMS_OUTPUT.PUT_LINE('PRECIO ' || V_DATOS_PRODUCTOS_PRO.PRECIO || '€');
    DBMS_OUTPUT.PUT_LINE('STOCK ' || V_DATOS_PRODUCTOS_PRO.STOCK);
    DBMS_OUTPUT.PUT_LINE('CATEGORIA ' || V_DATOS_PRODUCTOS_PRO.CATEGORIA);
    IF V_DATOS_PRODUCTOS_PRO.ACTIVO = 0 then
    V_ACTIVO_PRODUCTO:= 'NO';
    ELSE
    V_ACTIVO_PRODUCTO:= 'YES';
    end if;
    DBMS_OUTPUT.PUT_LINE('ACTIVO: ' || V_ACTIVO_PRODUCTO);

END P_DATOS_PRODUCTOS;

/
